import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, useUser, RedirectToSignIn, SignIn, SignedIn, } from '@clerk/nextjs'
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ClerkProvider>

        <html lang="en">
          <body className={inter.className}>
            <Header />
            {/* {console.log(children)} */}
            {/* Hello */}
            <main>
              {children}
            </main>

          </body>
        </html>

      </ClerkProvider>
    </>
  );
}
