import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ClerkProvider>

        <html lang="en">
          <body className={inter.className}>
            <Header />
            <main>
              {children}
            </main>
          </body>
        </html>

      </ClerkProvider>
    </>
  );
}
// <div class="h-56 grid grid-cols-3 gap-4 content-center">
// <!-- Your grid items go here -->
// </div>
